; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\tobias_huang\AppData\Local\Temp\.NETFramework,Version=4.5.2.AssemblyAttributes.cpp"
