; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\tobias_huang\AppData\Local\Temp\.NETFramework,Version=4.5.2.AssemblyAttributes.cpp"
